server {
    listen 80;
    server_name carte.coordination-defense-sante.org utop70.coordination-defense-sante.org;

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }

    location / {
        return 301 https://$server_name$request_uri;
    }
}
