# Uncomment this configuration after you obtained certificates
# otherwise nginx cannot start successfully because the ssl files cannot be find
# server {
#     listen 443 ssl;
#     server_name carte.coordination-defense-sante.org utop70.coordination-defense-sante.org;

#     ssl_certificate 	    /etc/letsencrypt/live/carte.coordination-defense-sante.com/fullchain.pem;
#     ssl_certificate_key   /etc/letsencrypt/live/carte.coordination-defense-sante.org/privkey.pem;
#
#    location / {
#	proxy_pass http://localhost:8080/;
#	proxy_set_header Host lizmap;
#	proxy_set_header X-Real-IP $remote_addr;
#       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#       proxy_set_header X-Forwarded-Proto $scheme;
#    }
#
# }
